version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - env/api.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
